/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author MR AL
 */
public class main extends javax.swing.JFrame {
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setResizable(false);
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        cari = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        keyword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        print1 = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tanggal Lahir", "Usia", "Berat", "Jenis Kelamin", "Tanggal Vaksin", "Harga", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldata.setOpaque(false);
        jScrollPane1.setViewportView(tbldata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 810, -1));

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 140, 30));

        refresh.setBackground(new java.awt.Color(51, 0, 255));
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 80, 30));

        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, 30));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 140, 30));

        Close.setBackground(new java.awt.Color(255, 0, 0));
        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 80, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Cattle Ranch");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 260, 60));

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Tanggal Lahir", "Tanggal Vaksin", "Harga", "Jenis_kelamin" }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });
        getContentPane().add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 180, 30));

        keyword.setToolTipText("Kata Kunci\n");
        getContentPane().add(keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 200, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Keyword");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 30));

        print1.setText("Print");
        print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print1ActionPerformed(evt);
            }
        });
        getContentPane().add(print1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 140, 30));

        insert.setBackground(new java.awt.Color(0, 153, 51));
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cari Berdasarkan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc_peternakan/image/sapi2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 680));

        setBounds(0, 0, 875, 723);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        
        selectData();
        
    }//GEN-LAST:event_refreshActionPerformed

    private void print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Data Peternakan");
       MessageFormat footer = new MessageFormat("Page (0,number,integer)    ");
       try{
           tbldata.print(JTable.PrintMode.FIT_WIDTH, header, footer,true, null, true, null);
           }catch(java.awt.print.PrinterException e){
               System.err.format("Cannot Print %s%n", e.getMessage());
       }
       
    }//GEN-LAST:event_print1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int baris = tbldata.getSelectedRow();
        if (baris != -1){
            String Id = tbldata.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_sapi WHERE id='"+Id+"'";
            int status = KoneksiDB.execute(SQL);
            if (status ==1){
               JOptionPane.showMessageDialog(this, "Data berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris data terlebih dahulu", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }selectData();           // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
         int baris = tbldata.getSelectedRow();
         insert i = new insert();
         
         String status;
        if (baris != -1){
            status = "update";
            String id = tbldata.getValueAt(baris, 0).toString();
            i.detail(status, id);
            i.show();
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris data terlebih dahulu", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_editActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
          String kolom[] = {"Id","Tanggal Lahir","Usia","Berat","Jenis Kelamin","Tanggal Vaksin","Harga", "Keterangan"};
          DefaultTableModel dtm= new DefaultTableModel(null,kolom);
          String SQL = "SELECT * FROM tb_sapi Where "+kategori.getSelectedItem()+" = '"+keyword.getText()+"'";
          ResultSet rs = KoneksiDB.executeQuery(SQL);
          try{
              while(rs.next()){
              String id = rs.getString(1);
              String tanggal_lahir = rs.getString(2);
              String usia = rs.getString(3);
              String berat = rs.getString(4);
              String jenis_kelamin = rs.getString(5);
              String tanggal_vaksin= rs.getString(6);
              String harga = rs.getString(7);
              String keterangan = rs.getString(8);
              String data[]={id,tanggal_lahir,usia,berat,jenis_kelamin,tanggal_vaksin,harga,keterangan};
              dtm.addRow(data);
              }
          }catch (SQLException ex){
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
       }
          tbldata.setModel(dtm);
          
    }//GEN-LAST:event_cariActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
       
    }//GEN-LAST:event_kategoriActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        new insert().show();
        setVisible(false);
    }//GEN-LAST:event_insertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                
              
            }
        });
    }
    
    public void selectData(){
          String kolom[] = {"Id","Tanggal Lahir","Usia","Berat","Jenis Kelamin","Tanggal Vaksin","Harga", "Keterangan"};
          DefaultTableModel dtm= new DefaultTableModel(null,kolom);
          String SQL = "SELECT * FROM tb_sapi";
          ResultSet rs = KoneksiDB.executeQuery(SQL);
          try{
              while(rs.next()){
              String id = rs.getString(1);
              String tanggal_lahir = rs.getString(2);
              String usia = rs.getString(3);
              String berat = rs.getString(4);
              String jenis_kelamin = rs.getString(5);
              String tanggal_vaksin= rs.getString(6);
              String harga = rs.getString(7);
              String keterangan = rs.getString(8);
              String data[]={id,tanggal_lahir,usia,berat,jenis_kelamin,tanggal_vaksin,harga,keterangan};
              dtm.addRow(data);
              }
          }catch (SQLException ex){
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
       }
          tbldata.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton cari;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField keyword;
    private javax.swing.JButton print1;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tbldata;
    // End of variables declaration//GEN-END:variables
}
